In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("/content/Zomato-data-.csv")
data

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [4]:
data.head(10)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
5,Timepass Dinner,Yes,No,3.8/5,286,600,Buffet
6,Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,8,800,Buffet
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
8,Penthouse Cafe,Yes,No,4.0/5,324,700,other
9,Smacznego,Yes,No,4.2/5,504,550,Cafes

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [7]:
data.describe()

             votes  approx_cost(for two people)
count   148.000000                   148.000000
mean    264.810811                   418.243243
std     653.676951                   223.085098
min       0.000000                   100.000000
25%       6.750000                   200.000000
50%      43.500000                   400.000000
75%     221.750000                   600.000000
max    4884.000000                   950.000000

In [8]:
data['listed_in(type)'].value_counts()

listed_in(type)
Dining    110
Cafes      23
other       8
Buffet      7
Name: count, dtype: int64

In [9]:
data.isna().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
approx_cost(for two people)    0
listed_in(type)                0
dtype: int64

In [10]:
data.duplicated().sum()

np.int64(0)

In [14]:
data['rate'].value_counts()

rate
3.8    20
3.7    15
3.3    14
3.4    12
4.1    11
3.6    11
4.0    10
3.9    10
4.2     8
3.2     7
3.1     7
2.9     7
3.5     6
3.0     2
4.6     2
2.8     2
4.4     2
4.3     1
2.6     1
Name: count, dtype: int64

In [15]:
data['rate'] = data['rate'].replace('/5','')
data['rate'] = data['rate'].astype(float)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    float64
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: float64(1), int64(2), object(4)
memory usage: 8.2+ KB

In [16]:
binary_cols = ['online_order','book_table']
for col in binary_cols:
  data[col] = data[col].map({'Yes':1,'No': 0})

In [17]:
data

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,1,1,4.1,775,800,Buffet
1,Spice Elephant,1,0,4.1,787,800,Buffet
2,San Churro Cafe,1,0,3.8,918,800,Buffet
3,Addhuri Udupi Bhojana,0,0,3.7,88,300,Buffet
4,Grand Village,0,0,3.8,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,0,0,3.3,0,100,Dining
144,New Indraprasta,0,0,3.3,0,150,Dining
145,Anna Kuteera,1,0,4.0,771,450,Dining
146,Darbar,0,0,3.0,98,800,Dining
147,Vijayalakshmi,1,0,3.9,47,200,Dining

In [19]:
data['votes'] = data['votes'].replace(0,data['votes'].median())
data['approx_cost(for two people)'] = data['approx_cost(for two people)'].replace(0,data['approx_cost(for two people)'].median())

In [20]:
data

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,1,1,4.1,775.0,800,Buffet
1,Spice Elephant,1,0,4.1,787.0,800,Buffet
2,San Churro Cafe,1,0,3.8,918.0,800,Buffet
3,Addhuri Udupi Bhojana,0,0,3.7,88.0,300,Buffet
4,Grand Village,0,0,3.8,166.0,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,0,0,3.3,43.5,100,Dining
144,New Indraprasta,0,0,3.3,43.5,150,Dining
145,Anna Kuteera,1,0,4.0,771.0,450,Dining
146,Darbar,0,0,3.0,98.0,800,Dining
147,Vijayalakshmi,1,0,3.9,47.0,200,Dining

In [22]:
data = data.drop('name',axis=1)

In [23]:
from sklearn.preprocessing import LabelEncoder
LB = LabelEncoder()
data['listed_in(type)'] = LB.fit_transform(data['listed_in(type)'])

In [24]:
data

,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,1,1,4.1,775.0,800,0
1,1,0,4.1,787.0,800,0
2,1,0,3.8,918.0,800,0
3,0,0,3.7,88.0,300,0
4,0,0,3.8,166.0,600,0
...,...,...,...,...,...,...
143,0,0,3.3,43.5,100,2
144,0,0,3.3,43.5,150,2
145,1,0,4.0,771.0,450,2
146,0,0,3.0,98.0,800,2
147,1,0,3.9,47.0,200,2

In [25]:
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler()
data[['votes' , 'approx_cost(for two people)']] = Scaler.fit_transform(data[['votes' , 'approx_cost(for two people)']])

In [26]:
data

,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,1,1,4.1,0.157992,0.823529,0
1,1,0,4.1,0.160451,0.823529,0
2,1,0,3.8,0.187295,0.823529,0
3,0,0,3.7,0.017213,0.235294,0
4,0,0,3.8,0.033197,0.588235,0
...,...,...,...,...,...,...
143,0,0,3.3,0.008094,0.000000,2
144,0,0,3.3,0.008094,0.058824,2
145,1,0,4.0,0.157172,0.411765,2
146,0,0,3.0,0.019262,0.823529,2
147,1,0,3.9,0.008811,0.117647,2

In [27]:
data[['votes' , 'approx_cost(for two people)']] = data[['votes' , 'approx_cost(for two people)']].round(3)

In [28]:
data

,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,1,1,4.1,0.158,0.824,0
1,1,0,4.1,0.160,0.824,0
2,1,0,3.8,0.187,0.824,0
3,0,0,3.7,0.017,0.235,0
4,0,0,3.8,0.033,0.588,0
...,...,...,...,...,...,...
143,0,0,3.3,0.008,0.000,2
144,0,0,3.3,0.008,0.059,2
145,1,0,4.0,0.157,0.412,2
146,0,0,3.0,0.019,0.824,2
147,1,0,3.9,0.009,0.118,2

In [29]:
data.corr()

,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
online_order,1.000000,0.236566,0.451562,0.352816,0.332706,-0.129947
book_table,0.236566,1.000000,0.330561,0.246168,0.296215,-0.071312
rate,0.451562,0.330561,1.000000,0.482827,0.275283,-0.105013
votes,0.352816,0.246168,0.482827,1.000000,0.314149,0.084029
approx_cost(for two people),0.332706,0.296215,0.275283,0.314149,1.000000,-0.226292
listed_in(type),-0.129947,-0.071312,-0.105013,0.084029,-0.226292,1.000000